# Generated by Django 6.0.3 on 2026-03-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highlited',
            new_name='highlighted',
        ),
    ]
